env:
  global:
    - CC_TEST_REPORTER_ID=d3a5392c036ac2c220667879ea20dfdea4999fb9c1c3fe7d9b1d39a4158f4043
language: java
jdk: openjdk11
sudo: false

notifications:
    email:
        - isaozturk@gmail.com

# public repo on Travis CI
after_success:
- mvn clean test jacoco:report coveralls:report
